import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { formatFooter, writeMetaFile } from '../generate-docs'

describe('formatFooter', () => {
  it('returns the correct format for a given date and version', () => {
    const date = new Date('2025-07-14T12:00:00.000Z')
    expect(formatFooter(date, '0.1.0')).toBe('Generated on 2025-07-14 from SDK v0.1.0')
  })

  it('uses UTC date, not local date', () => {
    // A moment just before midnight UTC but after midnight in UTC+1
    const date = new Date('2025-07-14T23:30:00.000Z')
    expect(formatFooter(date, '1.2.3')).toBe('Generated on 2025-07-14 from SDK v1.2.3')
  })

  it('includes the exact version string provided', () => {
    const date = new Date('2025-01-01T00:00:00.000Z')
    expect(formatFooter(date, '2.0.0-beta.1')).toBe('Generated on 2025-01-01 from SDK v2.0.0-beta.1')
  })

  it('handles boundary date: last day of month', () => {
    const date = new Date('2025-03-31T23:59:59.000Z')
    expect(formatFooter(date, '3.0.0')).toBe('Generated on 2025-03-31 from SDK v3.0.0')
  })
})

describe('writeMetaFile', () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'write-meta-test-'))
  })

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('writes _meta.ts with correct auto-generated header and satisfies clause', () => {
    fs.writeFileSync(path.join(tmpDir, 'classes.mdx'), '')
    writeMetaFile(tmpDir)
    const content = fs.readFileSync(path.join(tmpDir, '_meta.ts'), 'utf8')
    expect(content).toContain('// This file is auto-generated by scripts/generate-docs.ts — do not edit manually')
    expect(content).toContain('satisfies Record<string, string>')
  })

  it('includes one key per .mdx file, keyed by filename stem', () => {
    fs.writeFileSync(path.join(tmpDir, 'classes.mdx'), '')
    fs.writeFileSync(path.join(tmpDir, 'type-aliases.mdx'), '')
    writeMetaFile(tmpDir)
    const content = fs.readFileSync(path.join(tmpDir, '_meta.ts'), 'utf8')
    expect(content).toContain('"classes"')
    expect(content).toContain('"type-aliases"')
  })

  it('maps filename stems to title-cased labels', () => {
    fs.writeFileSync(path.join(tmpDir, 'type-aliases.mdx'), '')
    writeMetaFile(tmpDir)
    const content = fs.readFileSync(path.join(tmpDir, '_meta.ts'), 'utf8')
    expect(content).toContain('"Type Aliases"')
  })

  it('writes an empty object when no .mdx files are present', () => {
    writeMetaFile(tmpDir)
    const content = fs.readFileSync(path.join(tmpDir, '_meta.ts'), 'utf8')
    expect(content).toContain('export default {} satisfies Record<string, string>')
  })

  it('does not include non-.mdx files as keys', () => {
    fs.writeFileSync(path.join(tmpDir, 'classes.mdx'), '')
    fs.writeFileSync(path.join(tmpDir, 'README.md'), '')
    writeMetaFile(tmpDir)
    const content = fs.readFileSync(path.join(tmpDir, '_meta.ts'), 'utf8')
    expect(content).not.toContain('"README"')
    expect(content).not.toContain('"README.md"')
  })
})
