import { Command } from "commander";

const BASH_COMPLETION_SCRIPT = `#!/usr/bin/env bash
# ILN CLI bash completion script
# Generated by @invoice-liquidity/cli

_iln_completions() {
  local cur prev commands
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="submit fund pay status list history config compat xdr dashboard dev"

  case "\${prev}" in
    submit)
      COMPREPLY=( $(compgen -W "--payer --amount --due --rate --token --help" -- "\${cur}") )
      return 0
      ;;
    fund)
      COMPREPLY=( $(compgen -W "--id --amount --help" -- "\${cur}") )
      return 0
      ;;
    pay)
      COMPREPLY=( $(compgen -W "--id --help" -- "\${cur}") )
      return 0
      ;;
    status)
      COMPREPLY=( $(compgen -W "--id --help" -- "\${cur}") )
      return 0
      ;;
    list)
      COMPREPLY=( $(compgen -W "--address --help" -- "\${cur}") )
      return 0
      ;;
    history)
      COMPREPLY=( $(compgen -W "--address --id --action --limit --format --help" -- "\${cur}") )
      return 0
      ;;
    config)
      COMPREPLY=( $(compgen -W "--help" -- "\${cur}") )
      return 0
      ;;
    dev)
      COMPREPLY=( $(compgen -W "start stop reset status seed --help" -- "\${cur}") )
      return 0
      ;;
    compat)
      COMPREPLY=( $(compgen -W "check --help" -- "\${cur}") )
      return 0
      ;;
    xdr)
      COMPREPLY=( $(compgen -W "decode --help" -- "\${cur}") )
      return 0
      ;;
    dashboard)
      COMPREPLY=( $(compgen -W "--refresh --export --help" -- "\${cur}") )
      return 0
      ;;
    seed)
      COMPREPLY=( $(compgen -W "--scenario --count --token --help" -- "\${cur}") )
      return 0
      ;;
  esac

  if [[ "\${cur}" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json --help" -- "\${cur}") )
    return 0
  fi

  COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
  return 0
}

complete -F _iln_completions iln
`;

const ZSH_COMPLETION_SCRIPT = `#compdef iln
# ILN CLI zsh completion script
# Generated by @invoice-liquidity/cli

_iln() {
  local -a commands
  commands=(
    'submit:Submit a new invoice'
    'fund:Fund an invoice'
    'pay:Mark an invoice as paid'
    'status:Show invoice status'
    'list:List invoices by address'
    'history:Show invoice history'
    'config:Show protocol configuration'
    'compat:SDK and contract compatibility utilities'
    'xdr:Inspect Soroban XDR values'
    'dashboard:Launch real-time dashboard'
    'dev:Development utilities'
  )

  local -a dev_subcommands
  dev_subcommands=(
    'start:Start local development environment'
    'stop:Stop local development environment'
    'reset:Reset local development environment'
    'status:Show local environment status'
    'seed:Create and fund testnet accounts'
  )

  local -a compat_subcommands
  compat_subcommands=(
    'check:Check SDK compatibility'
  )

  local -a xdr_subcommands
  xdr_subcommands=(
    'decode:Decode base64 Soroban ScVal XDR'
  )

  _arguments -C \
    '--json[Reserved for future machine-readable output]' \
    '--help[Show help]' \
    '1:command:->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
        submit)
          _arguments \
            '--payer[Stellar address of the payer]:payer: ' \
            '--amount[Invoice amount in display units]:amount: ' \
            '--due[Due date as YYYY-MM-DD or Unix timestamp]:due: ' \
            '--rate[Discount rate in basis points]:rate: ' \
            '--token[Override token contract ID]:token: ' \
            '--help[Show help]'
          ;;
        fund)
          _arguments \
            '--id[Invoice ID]:id: ' \
            '--amount[Amount to fund in display units]:amount: ' \
            '--help[Show help]'
          ;;
        pay)
          _arguments \
            '--id[Invoice ID]:id: ' \
            '--help[Show help]'
          ;;
        status)
          _arguments \
            '--id[Invoice ID]:id: ' \
            '--help[Show help]'
          ;;
        list)
          _arguments \
            '--address[Stellar address to query]:address: ' \
            '--help[Show help]'
          ;;
        history)
          _arguments \
            '--address[Stellar address to query]:address: ' \
            '--id[Filter to specific invoice ID]:id: ' \
            '--action[Filter by action type]:action:(submit fund pay)' \
            '--limit[Maximum number of results]:limit: ' \
            '--format[Output format]:format:(table json)' \
            '--help[Show help]'
          ;;
        config)
          _arguments '--help[Show help]'
          ;;
        dev)
          _arguments -C \
            '1:subcommand:->subcommand' \
            '*::arg:->args'

          case $state in
            subcommand)
              _describe 'subcommand' dev_subcommands
              ;;
            args)
              case $words[1] in
                seed)
                  _arguments \
                    '--scenario[Seeding scenario]:scenario:(new-user active-lp disputed)' \
                    '--count[Number of records to seed]:count: ' \
                    '--token[Specific token to use]:token:(USDC EURC)' \
                    '--help[Show help]'
                  ;;
                *)
                  _arguments '--help[Show help]'
                  ;;
              esac
          esac
          ;;
        compat)
          _arguments -C \
            '1:subcommand:->subcommand' \
            '*::arg:->args'

          case $state in
            subcommand)
              _describe 'subcommand' compat_subcommands
              ;;
            args)
              _arguments '--help[Show help]'
              ;;
          esac
          ;;
        xdr)
          _arguments -C \
            '1:subcommand:->subcommand' \
            '*::arg:->args'

          case $state in
            subcommand)
              _describe 'subcommand' xdr_subcommands
              ;;
            args)
              _arguments \
                '[base64]:base64: ' \
                '--help[Show help]'
              ;;
          esac
          ;;
        dashboard)
          _arguments \
            '--refresh[Refresh interval in milliseconds]:refresh: ' \
            '--export[Export dashboard data to JSON file]:file: ' \
            '--help[Show help]'
          ;;
      esac
      ;;
  esac
}

_iln "$@"
`;

export function generateBashCompletion(): string {
  return BASH_COMPLETION_SCRIPT;
}

export function generateZshCompletion(): string {
  return ZSH_COMPLETION_SCRIPT;
}

export function registerCompletionCommand(program: Command): void {
  program
    .command("completion")
    .description("Generate shell completion scripts")
    .argument("[shell]", "shell type: bash or zsh", "bash")
    .action((shell: string) => {
      switch (shell) {
        case "bash":
          process.stdout.write(generateBashCompletion());
          break;
        case "zsh":
          process.stdout.write(generateZshCompletion());
          break;
        default:
          throw new Error(
            `Unsupported shell: ${shell}. Supported shells: bash, zsh`
          );
      }
    });
}
