name: E2E Integration

on: [push, pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: env.RUN_E2E == 'true'
    env:
      RUN_E2E: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Start Local Stellar Node
        run: docker-compose up -d
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Wait for RPC
        run: sleep 15 
        
      - name: Install & Run
        run: |
          npm install
          npm run test:e2e
